export const medicalRecords = [
  {
    id: "MR-001",
    patientName: "John Doe",
    patientId: "P-1001",
    dateOfBirth: "1985-04-12",
    gender: "Male",
    contactNumber: "+1-555-123-4567",
    email: "johndoe@example.com",
    appointmentDate: "2023-10-01",
    doctorName: "Dr. Emily Smith",
    doctorSpecialization: "Cardiology",
    diagnosis: "Hypertension",
    treatment: "Prescribed Lisinopril 10mg daily",
    medications: ["Lisinopril"],
    allergies: ["Penicillin"],
    createdAt: "2023-10-01T09:00:00",
    notes: "Patient advised to monitor blood pressure regularly.",
  },
  {
    id: "MR-002",
    patientName: "Jane Smith",
    patientId: "P-1002",
    dateOfBirth: "1990-07-25",
    gender: "Female",
    contactNumber: "+1-555-987-6543",
    email: "janesmith@example.com",
    appointmentDate: "2023-10-05",
    doctorName: "Dr. Michael Brown",
    doctorSpecialization: "Dermatology",
    diagnosis: "Acne Vulgaris",
    treatment: "Prescribed topical retinoid and oral antibiotics",
    medications: ["Tretinoin", "Doxycycline"],
    allergies: ["Sulfa drugs"],
    createdAt: "2023-10-05T09:00:00",
    notes: "Follow-up in 6 weeks.",
  },
  {
    id: "MR-003",
    patientName: "Alice Johnson",
    patientId: "P-1003",
    dateOfBirth: "1978-11-30",
    gender: "Female",
    contactNumber: "+1-555-456-7890",
    email: "alicej@example.com",
    appointmentDate: "2023-10-10",
    doctorName: "Dr. Robert Wilson",
    doctorSpecialization: "Orthopedics",
    diagnosis: "Osteoarthritis",
    treatment: "Physical therapy and prescribed NSAIDs",
    medications: ["Ibuprofen"],
    allergies: ["Aspirin"],
    createdAt: "2023-10-10T09:00:00",

    notes: "Patient to attend PT sessions twice a week.",
  },
  {
    id: "MR-004",
    patientName: "Bob Williams",
    patientId: "P-1004",
    dateOfBirth: "1982-03-15",
    gender: "Male",
    contactNumber: "+1-555-321-6547",
    email: "bobw@example.com",
    appointmentDate: "2023-10-12",
    doctorName: "Dr. Sarah Lee",
    doctorSpecialization: "Endocrinology",
    diagnosis: "Type 2 Diabetes",
    treatment: "Prescribed Metformin 500mg twice daily",
    medications: ["Metformin"],
    allergies: ["None"],
    notes: "Patient advised to follow a low-carb diet.",
    createdAt: "2023-10-12T09:00:00",
  },
  {
    id: "MR-005",
    patientName: "Charlie Brown",
    patientId: "P-1005",
    dateOfBirth: "1995-09-20",
    gender: "Male",
    contactNumber: "+1-555-654-3210",
    email: "charlieb@example.com",
    appointmentDate: "2023-10-15",
    doctorName: "Dr. Laura Green",
    doctorSpecialization: "Pediatrics",
    diagnosis: "Asthma",
    treatment: "Prescribed Albuterol inhaler",
    medications: ["Albuterol"],
    allergies: ["Dust mites"],
    notes: "Patient to use inhaler as needed.",
    createdAt: "2023-10-15T09:00:00",
  },
  {
    id: "MR-006",
    patientName: "Diana Prince",
    patientId: "P-1006",
    dateOfBirth: "1988-12-05",
    gender: "Female",
    contactNumber: "+1-555-789-1234",
    email: "dianap@example.com",
    appointmentDate: "2023-10-18",
    doctorName: "Dr. James Carter",
    doctorSpecialization: "Psychiatry",
    diagnosis: "Generalized Anxiety Disorder",
    treatment: "Prescribed Sertraline 50mg daily",
    medications: ["Sertraline"],
    allergies: ["None"],
    notes: "Patient to attend therapy sessions weekly.",
    createdAt: "2023-10-18T09:00:00",
  },
  {
    id: "MR-007",
    patientName: "Ethan Hunt",
    patientId: "P-1007",
    dateOfBirth: "1975-06-22",
    gender: "Male",
    contactNumber: "+1-555-234-5678",
    email: "ethanh@example.com",
    appointmentDate: "2023-10-20",
    doctorName: "Dr. Olivia White",
    doctorSpecialization: "Gastroenterology",
    diagnosis: "Gastroesophageal Reflux Disease (GERD)",
    treatment: "Prescribed Omeprazole 20mg daily",
    medications: ["Omeprazole"],
    allergies: ["None"],
    createdAt: "2023-10-20T09:00:00",
    notes: "Patient advised to avoid spicy foods.",
  },
  {
    id: "MR-008",
    patientName: "Fiona Gallagher",
    patientId: "P-1008",
    dateOfBirth: "1992-02-14",
    gender: "Female",
    contactNumber: "+1-555-876-5432",
    email: "fionag@example.com",
    appointmentDate: "2023-10-22",
    doctorName: "Dr. Daniel Harris",
    doctorSpecialization: "Neurology",
    diagnosis: "Migraine",
    treatment: "Prescribed Sumatriptan 50mg as needed",
    medications: ["Sumatriptan"],
    allergies: ["None"],
    createdAt: "2023-10-22T09:00:00",
    notes: "Patient to track migraine triggers.",
  },
  {
    id: "MR-009",
    patientName: "George King",
    patientId: "P-1009",
    dateOfBirth: "1980-08-10",
    gender: "Male",
    contactNumber: "+1-555-345-6789",
    email: "georgek@example.com",
    appointmentDate: "2023-10-25",
    doctorName: "Dr. Sophia Taylor",
    doctorSpecialization: "Oncology",
    diagnosis: "Melanoma",
    treatment: "Referred for surgical consultation",
    medications: ["None"],
    allergies: ["None"],
    createdAt: "2023-10-25T09:00:00",
    notes: "Patient to schedule surgery soon.",
  },
  {
    id: "MR-010",
    patientName: "Hannah Baker",
    patientId: "P-1010",
    dateOfBirth: "1998-05-18",
    gender: "Female",
    contactNumber: "+1-555-432-1098",
    email: "hannahb@example.com",
    appointmentDate: "2023-10-28",
    doctorName: "Dr. William Clark",
    doctorSpecialization: "Rheumatology",
    diagnosis: "Rheumatoid Arthritis",
    treatment: "Prescribed Methotrexate 7.5mg weekly",
    medications: ["Methotrexate"],
    allergies: ["None"],
    createdAt: "2023-10-28T09:00:00",
    notes: "Patient to monitor liver function regularly.",
  },
];
