export const availability = [
  {
    id: "avail1",
    doctorId: "doc1",
    date: new Date().toISOString(),
    createdAt: new Date(),
    updatedAt: new Date(),
    timeSlots: [
      {
        id: "slot1",
        availabilityId: "avail1",
        startTime: "09:00",
        endTime: "09:30",
        price: 100,
        type: "video",
        clinicId: "clinic1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "slot2",
        availabilityId: "avail1",
        startTime: "10:00",
        endTime: "10:30",
        price: 100,
        type: "consultation",
        clinicId: "clinic1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "slot3",
        availabilityId: "avail1",
        startTime: "10:00",
        endTime: "10:30",
        price: 100,
        type: "Audio",
        clinicId: "clinic1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "avail2",
    doctorId: "doc2",
    date: "2025-02-11",
    createdAt: new Date(),
    updatedAt: new Date(),
    timeSlots: [
      {
        id: "slot3",
        availabilityId: "avail2",
        startTime: "14:00",
        endTime: "14:30",
        price: 150,
        type: "consultation",
        clinicId: "clinic2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "slot4",
        availabilityId: "avail2",
        startTime: "15:00",
        endTime: "15:30",
        price: 150,
        type: "consultation",
        clinicId: "clinic2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "avail3",
    doctorId: "doc3",
    date: "2025-02-12",
    createdAt: new Date(),
    updatedAt: new Date(),
    timeSlots: [
      {
        id: "slot5",
        availabilityId: "avail3",
        startTime: "08:00",
        endTime: "08:30",
        price: 120,
        type: "consultation",
        clinicId: "clinic3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "slot6",
        availabilityId: "avail3",
        startTime: "13:00",
        endTime: "13:30",
        price: 120,
        type: "consultation",
        clinicId: "clinic3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "avail4",
    doctorId: "doc4",
    date: "2025-02-13",
    createdAt: new Date(),
    updatedAt: new Date(),
    timeSlots: [
      {
        id: "slot7",
        availabilityId: "avail4",
        startTime: "11:00",
        endTime: "11:30",
        price: 130,
        type: "consultation",
        clinicId: "clinic4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "slot8",
        availabilityId: "avail4",
        startTime: "16:00",
        endTime: "16:30",
        price: 130,
        type: "consultation",
        clinicId: "clinic4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];
