export const usersData = [
  {
    id: "1",
    userId: "user_cuid_123",
    name: "Dr. John Doe",
    email: "doctor@example.com",
    specialties: "Dental Care",
    earn: 2000,
    image: "/images/doctor-profile/doctor-1.jpg",
    password: "123456",
    role: "doctor",
    phoneNumber: "+1-234-567-8901",
    bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    displayName: "Dr. John Doe",
    addresses: {
      id: "address_cuid_123",
      address: "123 Main St, New York",
      city: "New York",
      state: "NY",
      country: "USA",
      zip: "10001",
    },
  },
  {
    id: "2",
    userId: "user_cuid_124",
    name: "Jane Smith",
    email: "patient@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-2.jpg",
    password: "123456",
    role: "patient",
    phoneNumber: "+1-234-567-8902",
    bio: "Patient with a passion for health and wellness.",
    displayName: "Jane Smith",
    addresses: {
      id: "address_cuid_124",
      address: "456 Elm St, Los Angeles",
      city: "Los Angeles",
      state: "CA",
      country: "USA",
      zip: "90001",
    },
  },
  {
    id: "3",
    userId: "user_cuid_125",
    name: "Pharmacy User",
    email: "pharmacy@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-3.jpg",
    password: "123456",
    role: "pharmacy-admin",
    phoneNumber: "+1-234-567-8903",
    bio: "Guest user exploring the platform.",
    displayName: "Guest User",
    addresses: {
      id: "address_cuid_125",
      address: "789 Oak St, Chicago",
      city: "Chicago",
      state: "IL",
      country: "USA",
      zip: "60601",
    },
  },
  {
    id: "4",
    userId: "user_cuid_126",
    name: "Dr. Emily Brown",
    email: "admin@example.com",
    specialties: "Cardiology",
    earn: 2500,
    image: "/images/doctor-profile/doctor-2.jpg",
    password: "123456",
    role: "admin",
    phoneNumber: "+1-234-567-8904",
    bio: "Cardiologist with over 10 years of experience.",
    displayName: "Dr. Emily Brown",
    addresses: {
      id: "address_cuid_126",
      address: "321 Pine St, Houston",
      city: "Houston",
      state: "TX",
      country: "USA",
      zip: "77001",
    },
  },
  {
    id: "5",
    userId: "user_cuid_127",
    name: "Michael Johnson",
    email: "michael@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-4.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "patient",
    phoneNumber: "+1-234-567-8905",
    bio: "Patient focused on maintaining a healthy lifestyle.",
    displayName: "Michael Johnson",
    addresses: {
      id: "address_cuid_127",
      address: "654 Cedar St, Phoenix",
      city: "Phoenix",
      state: "AZ",
      country: "USA",
      zip: "85001",
    },
  },
  {
    id: "6",
    userId: "user_cuid_128",
    name: "Guest User 2",
    email: "guest2@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-5.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "guest",
    phoneNumber: "+1-234-567-8906",
    bio: "Another guest user exploring the platform.",
    displayName: "Guest User 2",
    addresses: {
      id: "address_cuid_128",
      address: "987 Birch St, Philadelphia",
      city: "Philadelphia",
      state: "PA",
      country: "USA",
      zip: "19019",
    },
  },
  {
    id: "7",
    userId: "user_cuid_129",
    name: "Dr. Sarah Lee",
    email: "sarah@example.com",
    specialties: "Pediatrics",
    earn: 1800,
    image: "/images/doctor-profile/doctor-3.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "doctor",
    phoneNumber: "+1-234-567-8907",
    bio: "Pediatrician dedicated to children's health.",
    displayName: "Dr. Sarah Lee",
    addresses: {
      id: "address_cuid_129",
      address: "135 Maple St, San Antonio",
      city: "San Antonio",
      state: "TX",
      country: "USA",
      zip: "78201",
    },
  },
  {
    id: "8",
    userId: "user_cuid_130",
    name: "Laura Wilson",
    email: "laura@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-6.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "patient",
    phoneNumber: "+1-234-567-8908",
    bio: "Patient with a focus on mental health.",
    displayName: "Laura Wilson",
    addresses: {
      id: "address_cuid_130",
      address: "246 Walnut St, San Diego",
      city: "San Diego",
      state: "CA",
      country: "USA",
      zip: "92101",
    },
  },
  {
    id: "9",
    userId: "user_cuid_131",
    name: "Guest User 3",
    email: "guest3@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-7.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "guest",
    phoneNumber: "+1-234-567-8909",
    bio: "Guest user exploring health options.",
    displayName: "Guest User 3",
    addresses: {
      id: "address_cuid_131",
      address: "369 Cherry St, Dallas",
      city: "Dallas",
      state: "TX",
      country: "USA",
      zip: "75201",
    },
  },
  {
    id: "10",
    userId: "user_cuid_132",
    name: "Dr. Robert Green",
    email: "robert@example.com",
    specialties: "Orthopedics",
    earn: 2200,
    image: "/images/doctor-profile/doctor-4.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "doctor",
    phoneNumber: "+1-234-567-8910",
    bio: "Orthopedic surgeon specializing in sports injuries.",
    displayName: "Dr. Robert Green",
    addresses: {
      id: "address_cuid_132",
      address: "753 Spruce St, San Jose",
      city: "San Jose",
      state: "CA",
      country: "USA",
      zip: "95101",
    },
  },
  {
    id: "11",
    userId: "user_cuid_133",
    name: "David Martinez",
    email: "david@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-8.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "patient",
    phoneNumber: "+1-234-567-8911",
    bio: "Patient focused on physical therapy and recovery.",
    displayName: "David Martinez",
    addresses: {
      id: "address_cuid_133",
      address: "852 Fir St, Austin",
      city: "Austin",
      state: "TX",
      country: "USA",
      zip: "73301",
    },
  },
  {
    id: "12",
    userId: "user_cuid_134",
    name: "Guest User 4",
    email: "guest4@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-9.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "guest",
    phoneNumber: "+1-234-567-8912",
    bio: "Guest user exploring healthcare services.",
    displayName: "Guest User 4",
    addresses: {
      id: "address_cuid_134",
      address: "963 Pine St, Jacksonville",
      city: "Jacksonville",
      state: "FL",
      country: "USA",
      zip: "32099",
    },
  },
  {
    id: "13",
    userId: "user_cuid_135",
    name: "Dr. Lisa White",
    email: "lisa@example.com",
    specialties: "Dermatology",
    earn: 2100,
    image: "/images/doctor-profile/doctor-5.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "doctor",
    phoneNumber: "+1-234-567-8913",
    bio: "Dermatologist with expertise in skin care.",
    displayName: "Dr. Lisa White",
    addresses: {
      id: "address_cuid_135",
      address: "147 Oak St, San Francisco",
      city: "San Francisco",
      state: "CA",
      country: "USA",
      zip: "94101",
    },
  },
  {
    id: "14",
    userId: "user_cuid_136",
    name: "Sophia Garcia",
    email: "sophia@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-10.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "patient",
    phoneNumber: "+1-234-567-8914",
    bio: "Patient interested in holistic health.",
    displayName: "Sophia Garcia",
    addresses: {
      id: "address_cuid_136",
      address: "258 Elm St, Columbus",
      city: "Columbus",
      state: "OH",
      country: "USA",
      zip: "43201",
    },
  },
  {
    id: "15",
    userId: "user_cuid_137",
    name: "Guest User 5",
    email: "guest5@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-11.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "guest",
    phoneNumber: "+1-234-567-8915",
    bio: "Guest user exploring medical resources.",
    displayName: "Guest User 5",
    addresses: {
      id: "address_cuid_137",
      address: "369 Maple St, Indianapolis",
      city: "Indianapolis",
      state: "IN",
      country: "USA",
      zip: "46201",
    },
  },
  {
    id: "16",
    userId: "user_cuid_138",
    name: "Dr. Mark Taylor",
    email: "mark@example.com",
    specialties: "Neurology",
    earn: 2300,
    image: "/images/doctor-profile/doctor-6.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "doctor",
    phoneNumber: "+1-234-567-8916",
    bio: "Neurologist with a focus on brain health.",
    displayName: "Dr. Mark Taylor",
    addresses: {
      id: "address_cuid_138",
      address: "753 Cedar St, Fort Worth",
      city: "Fort Worth",
      state: "TX",
      country: "USA",
      zip: "76101",
    },
  },
  {
    id: "17",
    userId: "user_cuid_139",
    name: "Emma Brown",
    email: "emma@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-12.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "patient",
    phoneNumber: "+1-234-567-8917",
    bio: "Patient focused on preventive care.",
    displayName: "Emma Brown",
    addresses: {
      id: "address_cuid_139",
      address: "852 Pine St, Charlotte",
      city: "Charlotte",
      state: "NC",
      country: "USA",
      zip: "28201",
    },
  },
  {
    id: "18",
    userId: "user_cuid_140",
    name: "Guest User 6",
    email: "guest6@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-1.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "guest",
    phoneNumber: "+1-234-567-8918",
    bio: "Guest user exploring healthcare options.",
    displayName: "Guest User 6",
    addresses: {
      id: "address_cuid_140",
      address: "963 Oak St, Seattle",
      city: "Seattle",
      state: "WA",
      country: "USA",
      zip: "98101",
    },
  },
  {
    id: "19",
    userId: "user_cuid_141",
    name: "Dr. Olivia Harris",
    email: "olivia@example.com",
    specialties: "Oncology",
    earn: 2400,
    image: "/images/doctor-profile/doctor-7.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "doctor",
    phoneNumber: "+1-234-567-8919",
    bio: "Oncologist dedicated to cancer research.",
    displayName: "Dr. Olivia Harris",
    addresses: {
      id: "address_cuid_141",
      address: "147 Maple St, Denver",
      city: "Denver",
      state: "CO",
      country: "USA",
      zip: "80201",
    },
  },
  {
    id: "20",
    userId: "user_cuid_142",
    name: "Daniel Clark",
    email: "daniel@example.com",
    specialties: null,
    earn: 0,
    image: "/images/avatar/avatar-2.jpg",
    password: "$2b$10$encryptedpasswordhere",
    role: "patient",
    phoneNumber: "+1-234-567-8920",
    bio: "Patient focused on fitness and nutrition.",
    displayName: "Daniel Clark",
    addresses: {
      id: "address_cuid_142",
      address: "258 Cedar St, Washington",
      city: "Washington",
      state: "DC",
      country: "USA",
      zip: "20001",
    },
  },
];
type Address = {
  id: string;
  address: string;
  city: string;
  state: string;
  country: string;
  zip: string;
};

export type TUser = {
  id: string;
  userId: string;
  name: string;
  email: string;
  specialties: string | null;
  earn: number;
  image: string;
  password: string;
  role: string;
  phoneNumber: string;
  bio: string;
  displayName: string;
  addresses: Address;
};

export type UsersData = TUser[];
