export const prescriptions = [
  {
    id: 1,
    patientName: "John Doe",
    doctorImage: "/images/avatar/avatar-01.jpg",
    doctorName: "Dr. Emily Smith",
    date: "2023-10-01",
    medications: ["Lisinopril", "Metformin"],
    dosage: ["10mg daily", "500mg twice daily"],
    instructions: "Take Lisinopril in the morning and Metformin with meals.",
    status: "Active",
  },
  {
    id: 2,
    patientName: "Jane Smith",
    doctorImage: "/images/patients/jane-smith.jpg",
    doctorName: "Dr. Michael Brown",
    date: "2023-10-05",
    medications: ["Tretinoin", "Doxycycline"],
    dosage: ["Apply once daily", "100mg daily"],
    instructions: "Use Tretinoin at night and take Doxycycline with food.",
    status: "Active",
  },
  {
    id: 3,
    patientName: "Alice Johnson",
    doctorImage: "/images/patients/alice-johnson.jpg",
    doctorName: "Dr. Robert Wilson",
    date: "2023-10-10",
    medications: ["Ibuprofen"],
    dosage: ["400mg as needed"],
    instructions:
      "Take Ibuprofen for pain relief, not more than 3 times a day.",
    status: "Expired",
  },
  {
    id: 4,
    patientName: "Bob Williams",
    doctorImage: "/images/patients/bob-williams.jpg",
    doctorName: "Dr. Sarah Lee",
    date: "2023-10-12",
    medications: ["Omeprazole"],
    dosage: ["20mg daily"],
    instructions: "Take Omeprazole before breakfast.",
    status: "Active",
  },
  {
    id: 5,
    patientName: "Charlie Brown",
    doctorImage: "/images/patients/charlie-brown.jpg",
    doctorName: "Dr. Laura Green",
    date: "2023-10-15",
    medications: ["Albuterol"],
    dosage: ["2 puffs as needed"],
    instructions: "Use Albuterol inhaler for asthma symptoms.",
    status: "Active",
  },
  {
    id: 6,
    patientName: "Charlie Brown",
    doctorImage: "/images/patients/charlie-brown.jpg",
    doctorName: "Dr. Laura Green",
    date: "2023-10-15",
    medications: ["Albuterol"],
    dosage: ["2 puffs as needed"],
    instructions: "Use Albuterol inhaler for asthma symptoms.",
    status: "Active",
  },
  {
    id: 7,
    patientName: "Charlie Brown",
    doctorImage: "/images/patients/charlie-brown.jpg",
    doctorName: "Dr. Laura Green",
    date: "2023-10-15",
    medications: ["Albuterol"],
    dosage: ["2 puffs as needed"],
    instructions: "Use Albuterol inhaler for asthma symptoms.",
    status: "Active",
  },
  {
    id: 8,
    patientName: "Charlie Brown",
    doctorImage: "/images/patients/charlie-brown.jpg",
    doctorName: "Dr. Laura Green",
    date: "2023-10-15",
    medications: ["Albuterol"],
    dosage: ["2 puffs as needed"],
    instructions: "Use Albuterol inhaler for asthma symptoms.",
    status: "Active",
  },
  {
    id: 9,
    patientName: "Charlie Brown",
    doctorImage: "/images/patients/charlie-brown.jpg",
    doctorName: "Dr. Laura Green",
    date: "2023-10-15",
    medications: ["Albuterol"],
    dosage: ["2 puffs as needed"],
    instructions: "Use Albuterol inhaler for asthma symptoms.",
    status: "Active",
  },
  {
    id: 10,
    patientName: "Charlie Brown",
    doctorImage: "/images/patients/charlie-brown.jpg",
    doctorName: "Dr. Laura Green",
    date: "2023-10-15",
    medications: ["Albuterol"],
    dosage: ["2 puffs as needed"],
    instructions: "Use Albuterol inhaler for asthma symptoms.",
    status: "Active",
  },
];
