// Sample Doctor Data
export const reviews = [
  {
    id: 1,
    doctor: {
      name: "Dr. James Smith",
      specialty: "Cardiology",
      avatar: "/images/avatar/avatar-1.jpg",
    },
    patient: {
      name: "Sophia Johnson",
      phone: "+1 234 567 8901",
      avatar: "/images/avatar/avatar-2.jpg",
    },
    status: "approved",
    content: "Dr. Smith is very knowledgeable and patient. Highly recommend!",
    rating: 5,
    createdAt: new Date("2024-01-15T10:30:00"),
    updatedAt: new Date("2024-01-16T12:00:00"),
  },
  {
    id: 2,
    doctor: {
      name: "Dr. Emily Brown",
      specialty: "Dermatology",
      avatar: "/images/avatar/avatar-3.jpg",
    },
    patient: {
      name: "Michael Davis",
      phone: "+1 345 678 9012",
      avatar: "/images/avatar/avatar-4.jpg",
    },
    status: "pending",
    content: "Great dermatologist, helped me with my skin issues!",
    rating: 2.6,
    createdAt: new Date("2024-02-10T09:00:00"),
    updatedAt: new Date("2024-02-11T14:20:00"),
  },
  {
    id: 3,
    doctor: {
      name: "Dr. Olivia Martinez",
      specialty: "Pediatrics",
      avatar: "/images/avatar/avatar-5.jpg",
    },
    patient: {
      name: "Daniel Wilson",
      phone: "+1 456 789 0123",
      avatar: "/images/avatar/avatar-6.jpg",
    },
    status: "approved",
    content: "Very caring and excellent with kids!",
    rating: 5,
    createdAt: new Date("2024-03-05T08:15:00"),
    updatedAt: new Date("2024-03-06T09:45:00"),
  },
  {
    id: 4,
    doctor: {
      name: "Dr. William Davis",
      specialty: "Neurology",
      avatar: "/images/avatar/avatar-7.jpg",
    },
    patient: {
      name: "Ava Thomas",
      phone: "+1 567 890 1234",
      avatar: "/images/avatar/avatar-8.jpg",
    },
    status: "rejected",
    content: "Helped me a lot with my migraines. Fantastic doctor!",
    rating: 4,
    createdAt: new Date("2024-04-12T11:20:00"),
    updatedAt: new Date("2024-04-13T13:10:00"),
  },
  {
    id: 5,
    doctor: {
      name: "Dr. Sophia White",
      specialty: "Ophthalmology",
      avatar: "/images/avatar/avatar-9.jpg",
    },
    patient: {
      name: "Ethan Harris",
      phone: "+1 678 901 2345",
      avatar: "/images/avatar/avatar-10.jpg",
    },
    status: "approved",
    content: "Very professional and thorough eye examination.",
    rating: 5,
    createdAt: new Date("2024-05-22T15:45:00"),
    updatedAt: new Date("2024-05-23T16:30:00"),
  },
  {
    id: 6,
    doctor: {
      name: "Dr. Daniel Wilson",
      specialty: "Endocrinology",
      avatar: "/images/avatar/avatar-11.jpg",
    },
    patient: {
      name: "Mia Robinson",
      phone: "+1 789 012 3456",
      avatar: "/images/avatar/avatar-12.jpg",
    },
    status: "pending",
    content: "Helped me manage my diabetes effectively!",
    rating: 5,
    createdAt: new Date("2024-06-18T13:10:00"),
    updatedAt: new Date("2024-06-19T14:50:00"),
  },
  {
    id: 7,
    doctor: {
      name: "Dr. Ava Thomas",
      specialty: "Gastroenterology",
      avatar: "/images/avatar/avatar-12.jpg",
    },
    patient: {
      name: "James Carter",
      phone: "+1 890 123 4567",
      avatar: "/images/avatar/avatar-1.jpg",
    },
    status: "approved",
    content: "Provided great advice for my digestive health.",
    rating: 4,
    createdAt: new Date("2024-07-01T07:30:00"),
    updatedAt: new Date("2024-07-02T08:40:00"),
  },
  {
    id: 8,
    doctor: {
      name: "Dr. Ethan White",
      specialty: "Oncology",
      avatar: "/images/avatar/avatar-2.jpg",
    },
    patient: {
      name: "Isabella Scott",
      phone: "+1 901 234 5678",
      avatar: "/images/avatar/avatar-3.jpg",
    },
    status: "rejected",
    content: "Compassionate and very thorough in his approach.",
    rating: 5,
    createdAt: new Date("2024-08-09T18:20:00"),
    updatedAt: new Date("2024-08-10T19:50:00"),
  },
  {
    id: 9,
    doctor: {
      name: "Dr. Mia Harris",
      specialty: "Psychiatry",
      avatar: "/images/avatar/avatar-4.jpg",
    },
    patient: {
      name: "Logan Wright",
      phone: "+1 012 345 6789",
      avatar: "/images/avatar/avatar-5.jpg",
    },
    status: "approved",
    content: "Very understanding and patient, helped me a lot!",
    rating: 5,
    createdAt: new Date("2024-09-15T12:10:00"),
    updatedAt: new Date("2024-09-16T14:00:00"),
  },
  {
    id: 10,
    doctor: {
      name: "Dr. Charlotte Clark",
      specialty: "Rheumatology",
      avatar: "/images/avatar/avatar-6.jpg",
    },
    patient: {
      name: "Benjamin Lewis",
      phone: "+1 123 456 7890",
      avatar: "/images/avatar/avatar-7.jpg",
    },
    status: "pending",
    content: "Provided excellent treatment for my arthritis.",
    rating: 4,
    createdAt: new Date("2024-10-01T17:20:00"),
    updatedAt: new Date("2024-10-02T18:30:00"),
  },
];
