import image from "@/public/images/avatar/avatar-1.jpg";
import image2 from "@/public/images/avatar/avatar-2.jpg";
import image3 from "@/public/images/avatar/avatar-3.jpg";
import image4 from "@/public/images/avatar/avatar-4.jpg";
import { EmploymentType } from "@/types/common";
export const doctors = [
  {
    user: {
      id: "1",
      name: "Dr. John Doe",
      email: "john.doe@example.com",
      emailVerified: "2024-02-08T12:00:00Z",
      image: image,
      password: "$2b$10$hashedpassword1",
      role: "doctor",
      isTwoFactorEnabled: false,
      createdAt: "2024-02-08T12:00:00Z",
      updatedAt: "2024-02-08T12:00:00Z",
    },
    doctorProfile: {
      id: "doctor1",
      userId: "user1",
      phoneNumber: "+1234567890",
      bio: "Experienced cardiologist with a decade of service.",
      displayName: "Dr. John Doe",
      insurance: [
        {
          id: "ins1",
          doctorId: "doc1",
          name: "HealthCare Plus",
          insuranceType: "Health",
          thumbnail: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      addresses: {
        id: "address1",
        address: "123 Heartbeat Street",
        city: "New York",
        state: "NY",
        country: "USA",
        zip: "10001",
      },
      languages: [
        { id: "lang1", language: { id: "lang_en", name: "English" } },
      ],
      experience: [
        {
          id: "exp1",
          doctorId: "doc1",
          title: "Senior Cardiologist",
          organization: "NYC Heart Center",
          yearsOfExperience: "10",
          location: "New York",
          startDate: new Date("2014-06-01T00:00:00.000Z"),
          endDate: null,
          description:
            "Specializing in advanced heart treatments and surgeries.",
          employmentsType: "fulltime" as EmploymentType,
          currentlyWorking: true,
          thumbnail: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      treatments: [
        {
          id: "treatment1",
          description: "Angioplasty procedure",
          doctorId: "",
          price: "5000",
          specialty: { id: "specialty1", name: "Cardiology" },
        },
      ],
      reviews: [
        {
          id: "review1",
          patientId: "patient1",
          rating: 5,
          comment: "Very knowledgeable and professional.",
        },
      ],
      availability: [
        {
          id: "avail1",
          doctorId: "doc1",
          date: new Date().toISOString(),
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot1",
              availabilityId: "avail1",
              startTime: "09:00",
              endTime: "09:30",
              price: 100,
              type: "video",
              clinicId: "clinic1",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot2",
              availabilityId: "avail1",
              startTime: "10:00",
              endTime: "10:30",
              price: 100,
              type: "consultation",
              clinicId: "clinic1",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot3",
              availabilityId: "avail1",
              startTime: "10:00",
              endTime: "10:30",
              price: 100,
              type: "Audio",
              clinicId: "clinic1",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail2",
          doctorId: "doc2",
          date: "2025-02-11",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot3",
              availabilityId: "avail2",
              startTime: "14:00",
              endTime: "14:30",
              price: 150,
              type: "consultation",
              clinicId: "clinic2",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot4",
              availabilityId: "avail2",
              startTime: "15:00",
              endTime: "15:30",
              price: 150,
              type: "consultation",
              clinicId: "clinic2",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail3",
          doctorId: "doc3",
          date: "2025-02-12",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot5",
              availabilityId: "avail3",
              startTime: "08:00",
              endTime: "08:30",
              price: 120,
              type: "consultation",
              clinicId: "clinic3",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot6",
              availabilityId: "avail3",
              startTime: "13:00",
              endTime: "13:30",
              price: 120,
              type: "consultation",
              clinicId: "clinic3",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail4",
          doctorId: "doc4",
          date: "2025-02-13",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot7",
              availabilityId: "avail4",
              startTime: "11:00",
              endTime: "11:30",
              price: 130,
              type: "consultation",
              clinicId: "clinic4",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot8",
              availabilityId: "avail4",
              startTime: "16:00",
              endTime: "16:30",
              price: 130,
              type: "consultation",
              clinicId: "clinic4",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
      ],
      clinics: [
        {
          id: "cln1",
          doctorId: "doc1",
          name: "HealthCare Clinic",
          address: "123 Wellness Street, Cityville, CA",
          price: "100",
          latitude: "34.0522",
          longitude: "-118.2437",
          createdAt: new Date("2025-01-15T10:00:00.000Z"),
          updatedAt: new Date("2025-01-15T10:00:00.000Z"),
        },
        {
          id: "cln2",
          doctorId: "doc2",
          name: "Smile Dental Care",
          address: "456 Tooth Lane, Smile City, TX",
          price: "150",
          latitude: "29.7604",
          longitude: "-95.3698",
          createdAt: new Date("2025-01-18T09:30:00.000Z"),
          updatedAt: new Date("2025-01-18T09:30:00.000Z"),
        },
      ],
      awards: [
        {
          id: "aw1",
          doctorId: "doc1",
          name: "Best Pediatrician of the Year",
          organization: "Healthcare Excellence Awards",
          description: "Awarded for outstanding care in pediatric medicine.",
          date: new Date("2024-12-10T10:00:00.000Z"),
        },
        {
          id: "aw2",
          doctorId: "doc2",
          name: "Top Dental Surgeon",
          organization: "Global Health Summit",
          description: "Recognized for exceptional skill in oral surgery.",
          date: new Date("2025-01-20T12:00:00.000Z"),
        },
        {
          id: "aw3",
          doctorId: "doc3",
          name: "Best Family Physician",
          organization: "National Medical Awards",
          description:
            "Awarded for excellence in family medicine and patient care.",
          date: new Date("2025-02-01T14:30:00.000Z"),
        },
        {
          id: "aw4",
          doctorId: "doc4",
          name: "Innovator in Surgery",
          organization: "Medical Innovations Conference",
          description:
            "Awarded for developing a new technique in minimally invasive surgery.",
          date: new Date("2025-03-15T09:00:00.000Z"),
        },
      ],
    },
  },
  {
    user: {
      id: "2",
      name: "Dr. Jane Smith",
      email: "jane.smith@example.com",
      emailVerified: "2024-02-09T12:00:00Z",
      image: image2,
      password: "$2b$10$hashedpassword2",
      role: "doctor",
      isTwoFactorEnabled: false,
      createdAt: "2024-02-09T12:00:00Z",
      updatedAt: "2024-02-09T12:00:00Z",
    },
    doctorProfile: {
      id: "doctor2",
      userId: "user2",
      phoneNumber: "+9876543210",
      bio: "Pediatric specialist with a passion for children's health.",
      displayName: "Dr. Jane Smith",
      availability: [
        {
          id: "avail1",
          doctorId: "doc1",
          date: "2025-02-10",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot1",
              availabilityId: "avail1",
              startTime: "09:00",
              endTime: "09:30",
              price: 100,
              type: "consultation",
              clinicId: "clinic1",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot2",
              availabilityId: "avail1",
              startTime: "10:00",
              endTime: "10:30",
              price: 100,
              type: "consultation",
              clinicId: "clinic1",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail2",
          doctorId: "doc2",
          date: "2025-02-11",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot3",
              availabilityId: "avail2",
              startTime: "14:00",
              endTime: "14:30",
              price: 150,
              type: "consultation",
              clinicId: "clinic2",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot4",
              availabilityId: "avail2",
              startTime: "15:00",
              endTime: "15:30",
              price: 150,
              type: "consultation",
              clinicId: "clinic2",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail3",
          doctorId: "doc3",
          date: "2025-02-12",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot5",
              availabilityId: "avail3",
              startTime: "08:00",
              endTime: "08:30",
              price: 120,
              type: "consultation",
              clinicId: "clinic3",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot6",
              availabilityId: "avail3",
              startTime: "13:00",
              endTime: "13:30",
              price: 120,
              type: "consultation",
              clinicId: "clinic3",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail4",
          doctorId: "doc4",
          date: "2025-02-13",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot7",
              availabilityId: "avail4",
              startTime: "11:00",
              endTime: "11:30",
              price: 130,
              type: "consultation",
              clinicId: "clinic4",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot8",
              availabilityId: "avail4",
              startTime: "16:00",
              endTime: "16:30",
              price: 130,
              type: "consultation",
              clinicId: "clinic4",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
      ],
      insurance: [
        {
          id: "ins2",
          doctorId: "doc2",
          name: "MedCare Group",
          insuranceType: "Dental",
          thumbnail: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      addresses: {
        id: "address2",
        address: "456 Kids Care Ave",
        city: "Los Angeles",
        state: "CA",
        country: "USA",
        zip: "90001",
      },
      languages: [
        { id: "lang2", language: { id: "lang_en", name: "English" } },
        { id: "lang3", language: { id: "lang_es", name: "Spanish" } },
      ],
      experience: [
        {
          id: "exp4",
          doctorId: "doc4",
          title: "General Surgeon",
          organization: "Miami General Hospital",
          yearsOfExperience: "12",
          location: "Miami",
          startDate: new Date("2012-11-01T00:00:00.000Z"),
          endDate: new Date("2024-02-08T00:00:00.000Z"),
          description: "Performing surgeries in a variety of medical fields.",
          employmentsType: "fulltime" as EmploymentType,
          currentlyWorking: false,
          thumbnail: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      treatments: [
        {
          id: "treatment2",
          description: "Routine Child Check-up",
          doctorId: "1",
          price: "200",
          specialty: { id: "specialty2", name: "Pediatrics" },
        },
      ],
      reviews: [
        {
          id: "review2",
          patientId: "patient2",
          rating: 4,
          comment: "Great with kids, highly recommended!",
        },
      ],
      clinics: [
        {
          id: "cln1",
          doctorId: "doc1",
          name: "HealthCare Clinic",
          address: "123 Wellness Street, Cityville, CA",
          price: "100",
          latitude: "34.0522",
          longitude: "-118.2437",
          createdAt: new Date("2025-01-15T10:00:00.000Z"),
          updatedAt: new Date("2025-01-15T10:00:00.000Z"),
        },
        {
          id: "cln2",
          doctorId: "doc2",
          name: "Smile Dental Care",
          address: "456 Tooth Lane, Smile City, TX",
          price: "150",
          latitude: "29.7604",
          longitude: "-95.3698",
          createdAt: new Date("2025-01-18T09:30:00.000Z"),
          updatedAt: new Date("2025-01-18T09:30:00.000Z"),
        },
      ],
      awards: [
        {
          id: "aw1",
          doctorId: "doc1",
          name: "Best Pediatrician of the Year",
          organization: "Healthcare Excellence Awards",
          description: "Awarded for outstanding care in pediatric medicine.",
          date: new Date("2024-12-10T10:00:00.000Z"),
        },
        {
          id: "aw2",
          doctorId: "doc2",
          name: "Top Dental Surgeon",
          organization: "Global Health Summit",
          description: "Recognized for exceptional skill in oral surgery.",
          date: new Date("2025-01-20T12:00:00.000Z"),
        },
        {
          id: "aw3",
          doctorId: "doc3",
          name: "Best Family Physician",
          organization: "National Medical Awards",
          description:
            "Awarded for excellence in family medicine and patient care.",
          date: new Date("2025-02-01T14:30:00.000Z"),
        },
        {
          id: "aw4",
          doctorId: "doc4",
          name: "Innovator in Surgery",
          organization: "Medical Innovations Conference",
          description:
            "Awarded for developing a new technique in minimally invasive surgery.",
          date: new Date("2025-03-15T09:00:00.000Z"),
        },
      ],
    },
  },
  {
    user: {
      id: "3",
      name: "Dr. Alan Walker",
      email: "alan.walker@example.com",
      emailVerified: "2024-02-10T12:00:00Z",
      image: image3,
      password: "$2b$10$hashedpassword3",
      role: "doctor",
      isTwoFactorEnabled: true,
      createdAt: "2024-02-10T12:00:00Z",
      updatedAt: "2024-02-10T12:00:00Z",
    },
    doctorProfile: {
      id: "doctor3",
      userId: "user3",
      phoneNumber: "+1122334455",
      bio: "Orthopedic surgeon specializing in sports injuries.",
      displayName: "Dr. Alan Walker",
      availability: [
        {
          id: "avail1",
          doctorId: "doc1",
          date: "2025-02-10",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot1",
              availabilityId: "avail1",
              startTime: "09:00",
              endTime: "09:30",
              price: 100,
              type: "consultation",
              clinicId: "clinic1",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot2",
              availabilityId: "avail1",
              startTime: "10:00",
              endTime: "10:30",
              price: 100,
              type: "consultation",
              clinicId: "clinic1",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail2",
          doctorId: "doc2",
          date: "2025-02-11",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot3",
              availabilityId: "avail2",
              startTime: "14:00",
              endTime: "14:30",
              price: 150,
              type: "consultation",
              clinicId: "clinic2",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot4",
              availabilityId: "avail2",
              startTime: "15:00",
              endTime: "15:30",
              price: 150,
              type: "consultation",
              clinicId: "clinic2",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail3",
          doctorId: "doc3",
          date: "2025-02-12",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot5",
              availabilityId: "avail3",
              startTime: "08:00",
              endTime: "08:30",
              price: 120,
              type: "consultation",
              clinicId: "clinic3",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot6",
              availabilityId: "avail3",
              startTime: "13:00",
              endTime: "13:30",
              price: 120,
              type: "consultation",
              clinicId: "clinic3",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail4",
          doctorId: "doc4",
          date: "2025-02-13",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot7",
              availabilityId: "avail4",
              startTime: "11:00",
              endTime: "11:30",
              price: 130,
              type: "consultation",
              clinicId: "clinic4",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot8",
              availabilityId: "avail4",
              startTime: "16:00",
              endTime: "16:30",
              price: 130,
              type: "consultation",
              clinicId: "clinic4",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
      ],
      insurance: [
        {
          id: "ins3",
          doctorId: "doc3",
          name: "LifeWell Insurance",
          insuranceType: "Life",
          thumbnail: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      addresses: {
        id: "address3",
        address: "789 Bone Fix Road",
        city: "Chicago",
        state: "IL",
        country: "USA",
        zip: "60601",
      },
      languages: [
        { id: "lang4", language: { id: "lang_en", name: "English" } },
      ],
      experience: [
        {
          id: "exp3",
          doctorId: "doc3",
          title: "Pediatrician",
          organization: "Children's Health Clinic",
          yearsOfExperience: "8",
          location: "Chicago",
          startDate: new Date("2015-08-10T00:00:00.000Z"),
          endDate: null,
          description: "Caring for children from birth through adolescence.",
          employmentsType: "fulltime" as EmploymentType,
          currentlyWorking: true,
          thumbnail: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      treatments: [
        {
          id: "treatment3",
          description: "Knee Replacement Surgery",
          doctorId: "",
          price: "10000",
          specialty: { id: "specialty3", name: "Orthopedics" },
        },
      ],
      reviews: [
        {
          id: "review3",
          patientId: "patient3",
          rating: 5,
          comment: "Helped me recover quickly from my knee injury!",
        },
      ],
      clinics: [
        {
          id: "cln1",
          doctorId: "doc1",
          name: "HealthCare Clinic",
          address: "123 Wellness Street, Cityville, CA",
          price: "100",
          latitude: "34.0522",
          longitude: "-118.2437",
          createdAt: new Date("2025-01-15T10:00:00.000Z"),
          updatedAt: new Date("2025-01-15T10:00:00.000Z"),
        },
        {
          id: "cln2",
          doctorId: "doc2",
          name: "Smile Dental Care",
          address: "456 Tooth Lane, Smile City, TX",
          price: "150",
          latitude: "29.7604",
          longitude: "-95.3698",
          createdAt: new Date("2025-01-18T09:30:00.000Z"),
          updatedAt: new Date("2025-01-18T09:30:00.000Z"),
        },
      ],
      awards: [
        {
          id: "aw1",
          doctorId: "doc1",
          name: "Best Pediatrician of the Year",
          organization: "Healthcare Excellence Awards",
          description: "Awarded for outstanding care in pediatric medicine.",
          date: new Date("2024-12-10T10:00:00.000Z"),
        },
        {
          id: "aw2",
          doctorId: "doc2",
          name: "Top Dental Surgeon",
          organization: "Global Health Summit",
          description: "Recognized for exceptional skill in oral surgery.",
          date: new Date("2025-01-20T12:00:00.000Z"),
        },
        {
          id: "aw3",
          doctorId: "doc3",
          name: "Best Family Physician",
          organization: "National Medical Awards",
          description:
            "Awarded for excellence in family medicine and patient care.",
          date: new Date("2025-02-01T14:30:00.000Z"),
        },
        {
          id: "aw4",
          doctorId: "doc4",
          name: "Innovator in Surgery",
          organization: "Medical Innovations Conference",
          description:
            "Awarded for developing a new technique in minimally invasive surgery.",
          date: new Date("2025-03-15T09:00:00.000Z"),
        },
      ],
    },
  },
  {
    user: {
      id: "4",
      name: "Dr. Emily Carter",
      email: "emily.carter@example.com",
      emailVerified: "2024-02-11T12:00:00Z",
      image: image4,
      password: "$2b$10$hashedpassword4",
      role: "doctor",
      isTwoFactorEnabled: true,
      createdAt: "2024-02-11T12:00:00Z",
      updatedAt: "2024-02-11T12:00:00Z",
    },
    doctorProfile: {
      id: "doctor4",
      userId: "user4",
      phoneNumber: "+15556667777",
      bio: "Dermatologist specializing in skin care and cosmetic treatments.",
      displayName: "Dr. Emily Carter",
      availability: [
        {
          id: "avail1",
          doctorId: "doc1",
          date: "2025-02-10T18:00:00.000Z",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot1",
              availabilityId: "avail1",
              startTime: "09:00",
              endTime: "09:30",
              price: 100,
              type: "consultation",
              clinicId: "clinic1",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot2",
              availabilityId: "avail1",
              startTime: "10:00",
              endTime: "10:30",
              price: 100,
              type: "consultation",
              clinicId: "clinic1",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail2",
          doctorId: "doc2",
          date: "2025-02-11",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot3",
              availabilityId: "avail2",
              startTime: "14:00",
              endTime: "14:30",
              price: 150,
              type: "consultation",
              clinicId: "clinic2",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot4",
              availabilityId: "avail2",
              startTime: "15:00",
              endTime: "15:30",
              price: 150,
              type: "consultation",
              clinicId: "clinic2",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail3",
          doctorId: "doc3",
          date: "2025-02-12",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot5",
              availabilityId: "avail3",
              startTime: "08:00",
              endTime: "08:30",
              price: 120,
              type: "consultation",
              clinicId: "clinic3",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot6",
              availabilityId: "avail3",
              startTime: "13:00",
              endTime: "13:30",
              price: 120,
              type: "consultation",
              clinicId: "clinic3",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: "avail4",
          doctorId: "doc4",
          date: "2025-02-13",
          createdAt: new Date(),
          updatedAt: new Date(),
          timeSlots: [
            {
              id: "slot7",
              availabilityId: "avail4",
              startTime: "11:00",
              endTime: "11:30",
              price: 130,
              type: "consultation",
              clinicId: "clinic4",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: "slot8",
              availabilityId: "avail4",
              startTime: "16:00",
              endTime: "16:30",
              price: 130,
              type: "consultation",
              clinicId: "clinic4",
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
      ],
      insurance: [
        {
          id: "ins4",
          doctorId: "doc4",
          name: "PremiumHealth",
          insuranceType: "Vision",
          thumbnail: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      addresses: {
        id: "address4",
        address: "101 Skin Glow Blvd",
        city: "Miami",
        state: "FL",
        country: "USA",
        zip: "33101",
      },
      languages: [
        { id: "lang5", language: { id: "lang_en", name: "English" } },
        { id: "lang6", language: { id: "lang_fr", name: "French" } },
      ],
      experience: [
        {
          id: "exp2",
          doctorId: "doc2",
          title: "Orthopedic Surgeon",
          organization: "Los Angeles Medical Center",
          yearsOfExperience: "15",
          location: "Los Angeles",
          startDate: new Date("2009-03-15T00:00:00.000Z"),
          endDate: new Date("2020-05-20T00:00:00.000Z"),
          description: "Experienced in joint replacement surgeries.",
          employmentsType: "fulltime" as EmploymentType,
          currentlyWorking: false,
          thumbnail: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      treatments: [
        {
          id: "treatment4",
          description: "Laser Skin Rejuvenation",
          doctorId: "",
          price: "1200",
          specialty: { id: "specialty4", name: "Dermatology" },
        },
      ],
      reviews: [
        {
          id: "review4",
          patientId: "patient4",
          rating: 5,
          comment: "My skin has never looked better! Highly recommend.",
        },
      ],
      clinics: [
        {
          id: "cln1",
          doctorId: "doc1",
          name: "HealthCare Clinic",
          address: "123 Wellness Street, Cityville, CA",
          price: "100",
          latitude: "34.0522",
          longitude: "-118.2437",
          createdAt: new Date("2025-01-15T10:00:00.000Z"),
          updatedAt: new Date("2025-01-15T10:00:00.000Z"),
        },
        {
          id: "cln2",
          doctorId: "doc2",
          name: "Smile Dental Care",
          address: "456 Tooth Lane, Smile City, TX",
          price: "150",
          latitude: "29.7604",
          longitude: "-95.3698",
          createdAt: new Date("2025-01-18T09:30:00.000Z"),
          updatedAt: new Date("2025-01-18T09:30:00.000Z"),
        },
      ],
      awards: [
        {
          id: "aw1",
          doctorId: "doc1",
          name: "Best Pediatrician of the Year",
          organization: "Healthcare Excellence Awards",
          description: "Awarded for outstanding care in pediatric medicine.",
          date: new Date("2024-12-10T10:00:00.000Z"),
        },
        {
          id: "aw2",
          doctorId: "doc2",
          name: "Top Dental Surgeon",
          organization: "Global Health Summit",
          description: "Recognized for exceptional skill in oral surgery.",
          date: new Date("2025-01-20T12:00:00.000Z"),
        },
        {
          id: "aw3",
          doctorId: "doc3",
          name: "Best Family Physician",
          organization: "National Medical Awards",
          description:
            "Awarded for excellence in family medicine and patient care.",
          date: new Date("2025-02-01T14:30:00.000Z"),
        },
        {
          id: "aw4",
          doctorId: "doc4",
          name: "Innovator in Surgery",
          organization: "Medical Innovations Conference",
          description:
            "Awarded for developing a new technique in minimally invasive surgery.",
          date: new Date("2025-03-15T09:00:00.000Z"),
        },
      ],
    },
  },
];
