export const data = [
  {
    id: "01",
    page: "www.facebook.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "9,636",
    link: "/",
  },
  {
    id: "02",
    page: "www.linkedin.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "7,636",
    link: "/",
  },
  {
    id: "03",
    page: "www.twitter.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "04",
    page: "www.twitter.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "05",
    page: "www.pinterest.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "06",
    page: "www.twitter.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "07",
    page: "www.youtube.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "08",
    page: "www.linkedin.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "09",
    page: "www.twitter.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "10",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "11",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "12",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "13",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "14",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "15",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "16",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "17",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "18",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "19",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "20",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
  {
    id: "21",
    page: "www.github.com",
    post: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    count: "5,636",
    link: "/",
  },
];
export const appointments = [
  {
    id: 1,
    image: "/images/avatar/avatar-1.jpg",
    patientName: "John Doe",
    age: 32,
    gender: "Male",
    doctor: "Dr. Emily Carter",
    department: "General Medicine",
    appointmentDate: "20-10-2025",
    appointmentTime: "10:30 AM",
    status: "Paid",
    isComplate: false,
    contact: "+1 234 567 890",
  },
  {
    id: 2,
    image: "/images/avatar/avatar-2.jpg",
    patientName: "Jane Smith",
    age: 28,
    gender: "Female",
    doctor: "Dr. William Brown",
    department: "Cardiology",
    appointmentDate: "21-10-2025",
    appointmentTime: "02:00 PM",
    status: "Unpaid",
    isComplate: false,
    contact: "+1 345 678 901",
  },
  {
    id: 3,
    image: "/images/avatar/avatar-3.jpg",
    patientName: "Michael Johnson",
    age: 40,
    gender: "Male",
    doctor: "Dr. Olivia Wilson",
    department: "Dental",
    appointmentDate: "22-10-2025",
    appointmentTime: "09:00 AM",
    status: "Paid",
    isComplate: true,
    contact: "+1 456 789 012",
  },
  {
    id: 4,
    image: "/images/avatar/avatar-4.jpg",
    patientName: "Emily Davis",
    age: 35,
    gender: "Female",
    doctor: "Dr. Christopher Lee",
    department: "Dermatology",
    appointmentDate: "23-10-2025",
    appointmentTime: "11:45 AM",
    status: "Paid",
    isComplate: true,
    contact: "+1 567 890 123",
  },
  {
    id: 5,
    image: "/images/avatar/avatar-5.jpg",
    patientName: "Daniel Brown",
    age: 50,
    gender: "Male",
    doctor: "Dr. Sarah Johnson",
    department: "Surgery",
    appointmentDate: "24-10-2025",
    appointmentTime: "03:30 PM",
    status: "Unpaid",
    isComplate: false,
    contact: "+1 678 901 234",
  },
  // {
  //   id: 6,
  //   image: "/images/avatar/avatar-6.jpg",
  //   patientName: "Sophia Wilson",
  //   age: 45,
  //   gender: "Female",
  //   doctor: "Dr. James Anderson",
  //   department: "Neurology",
  //   appointmentDate: "25-10-2025",
  //   appointmentTime: "01:15 PM",
  //   status: "Pending",
  //   contact: "+1 789 012 345",
  // },
  // {
  //   id: 7,
  //   image: "/images/avatar/avatar-7.jpg",
  //   patientName: "Christopher Martinez",
  //   age: 37,
  //   gender: "Male",
  //   doctor: "Dr. Emma Thomas",
  //   department: "Check-up",
  //   appointmentDate: "26-10-2025",
  //   appointmentTime: "08:30 AM",
  //   status: "Confirmed",
  //   contact: "+1 890 123 456",
  // },
  // {
  //   id: 8,
  //   image: "/images/avatar/avatar-8.jpg",
  //   patientName: "Olivia Taylor",
  //   age: 29,
  //   gender: "Female",
  //   doctor: "Dr. Henry Wilson",
  //   department: "Emergency",
  //   appointmentDate: "27-10-2025",
  //   appointmentTime: "04:00 PM",
  //   status: "Completed",
  //   contact: "+1 901 234 567",
  // },
  // {
  //   id: 9,
  //   image: "/images/avatar/avatar-9.jpg",
  //   patientName: "James Anderson",
  //   age: 55,
  //   gender: "Male",
  //   doctor: "Dr. Isabella White",
  //   department: "Orthopedics",
  //   appointmentDate: "28-10-2025",
  //   appointmentTime: "07:00 PM",
  //   status: "Cancelled",
  //   contact: "+1 012 345 678",
  // },
  // {
  //   id: 10,
  //   image: "/images/avatar/avatar-10.jpg",
  //   patientName: "Emma Thomas",
  //   age: 31,
  //   gender: "Female",
  //   doctor: "Dr. Daniel Parker",
  //   department: "Consultation",
  //   appointmentDate: "29-10-2025",
  //   appointmentTime: "06:30 AM",
  //   status: "Confirmed",
  //   contact: "+1 123 456 789",
  // },
];
export const clinics = [
  {
    id: 1,
    name: "Sunrise Medical Center",
    link: "www.sunrisemedical.com",
    total: "4963",
    image: "/images/clinic/clinic-6.jpg",
    address: "123 Sunrise Blvd, New York, NY 10001",
    phoneNumber: "+1 (555) 123-4567",
    email: "info@sunrisemedical.com",
    services: ["General Medicine", "Pediatrics", "Cardiology", "Dermatology"],
    rating: 4.8,
    openingHours: {
      Monday: "8:00 AM - 6:00 PM",

      Friday: "8:00 AM - 6:00 PM",
      Saturday: "9:00 AM - 4:00 PM",
    },
    socialMedia: {
      facebook: "https://facebook.com/sunrisemedical",
      twitter: "https://twitter.com/sunrisemedical",
      instagram: "https://instagram.com/sunrisemedical",
    },
  },
  {
    id: 2,
    name: "Wellness Care Hospital",
    link: "www.wellnesscare.com",
    total: "2963",
    image: "/images/clinic/clinic-7.jpg",
    address: "456 Wellness Ave, Los Angeles, CA 90001",
    phoneNumber: "+1 (555) 987-6543",
    email: "contact@wellnesscare.com",
    services: ["Orthopedics", "Neurology", "Oncology", "Physical Therapy"],
    rating: 4.6,
    openingHours: {
      Tuesday: "7:00 AM - 7:00 PM",

      Friday: "7:00 AM - 7:00 PM",
      Saturday: "8:00 AM - 5:00 PM",
    },
    socialMedia: {
      facebook: "https://facebook.com/wellnesscare",
      twitter: "https://twitter.com/wellnesscare",
      instagram: "https://instagram.com/wellnesscare",
    },
  },
  {
    id: 3,
    name: "City Health Clinic",
    link: "www.cityhealth.com",
    total: "1963",
    image: "/images/clinic/clinic-8.jpg",
    address: "789 City St, Chicago, IL 60601",
    phoneNumber: "+1 (555) 456-7890",
    email: "support@cityhealth.com",
    services: ["Dentistry", "Optometry", "Gynecology", "Mental Health"],
    rating: 4.7,
    openingHours: {
      Friday: "9:00 AM - 5:00 PM",
      Saturday: "10:00 AM - 3:00 PM",
    },
    socialMedia: {
      facebook: "https://facebook.com/cityhealth",
      twitter: "https://twitter.com/cityhealth",
      instagram: "https://instagram.com/cityhealth",
    },
  },
];
export const invoices = [
  {
    id: 1,
    invoiceNumber: "INV-2024-001",
    status: "Paid",
    amount: 286.2,
    paymentMethod: "Credit Card",
    paymentDate: "2024-03-20",
    billTo: {
      name: "John Doe",
      image: "/images/avatar/avatar-6.jpg",
    },
  },
  {
    id: 2,
    invoiceNumber: "INV-2024-002",
    status: "Unpaid",
    amount: 413.4,
    paymentMethod: "Bank Transfer",
    paymentDate: "2024-03-22",
    billTo: {
      name: "Jane Smith",
      image: "/images/avatar/avatar-7.jpg",
    },
  },
  {
    id: 3,
    invoiceNumber: "INV-2024-003",
    status: "Paid",
    amount: 148.4,
    paymentMethod: "Cash",
    paymentDate: "2024-03-30", // Not paid yet
    billTo: {
      name: "Alice Johnson",
      image: "/images/avatar/avatar-8.jpg",
    },
  },
  {
    id: 4,
    invoiceNumber: "INV-2024-004",
    status: "Unpaid",
    amount: 320.5,
    paymentMethod: "Credit Card",
    paymentDate: null, // Not paid yet
    billTo: {
      name: "Michael Brown",
      image: "/images/avatar/avatar-9.jpg",
    },
  },
  {
    id: 5,
    invoiceNumber: "INV-2024-005",
    status: "Overdue",
    amount: 95.0,
    paymentMethod: "Bank Transfer",
    paymentDate: "2024-03-27", // Not paid yet
    billTo: {
      name: "Emily Davis",
      image: "/images/avatar/avatar-10.jpg",
    },
  },
  {
    id: 6,
    invoiceNumber: "INV-2024-006",
    status: "Paid",
    amount: 450.75,
    paymentMethod: "PayPal",
    paymentDate: "2024-03-25",
    billTo: {
      name: "David Wilson",
      image: "/images/avatar/avatar-11.jpg",
    },
  },
];
