export const appointments = [
  {
    id: 1,
    image: "/images/avatar/avatar-1.jpg",
    patientName: "John Doe",
    age: 32,
    gender: "Male",
    doctor: "Dr. Emily Carter",
    department: "General Medicine",
    appointmentDate: "20-10-2025",
    appointmentTime: "10:30 AM",
    amount: 200,
    status: "Paid",
    isComplate: true,
    contact: "+1 234 567 890",
  },
  {
    id: 2,
    image: "/images/avatar/avatar-2.jpg",
    patientName: "Jane Smith",
    age: 28,
    gender: "Female",
    amount: 150,
    doctor: "Dr. William Brown",
    department: "Cardiology",
    appointmentDate: "21-10-2025",
    appointmentTime: "02:00 PM",
    status: "Unpaid",
    isComplate: false,
    contact: "+1 345 678 901",
  },
  {
    id: 3,
    image: "/images/avatar/avatar-3.jpg",
    patientName: "Michael Johnson",
    age: 40,
    gender: "Male",
    doctor: "Dr. Olivia Wilson",
    amount: 100,
    department: "Dental",
    appointmentDate: "22-10-2025",
    appointmentTime: "09:00 AM",
    status: "Paid",
    isComplate: true,
    contact: "+1 456 789 012",
  },
  {
    id: 4,
    image: "/images/avatar/avatar-4.jpg",
    patientName: "Emily Davis",
    age: 35,
    gender: "Female",
    amount: 250,
    doctor: "Dr. Christopher Lee",
    department: "Dermatology",
    appointmentDate: "23-10-2025",
    appointmentTime: "11:45 AM",
    status: "Paid",
    isComplate: true,
    contact: "+1 567 890 123",
  },
  {
    id: 5,
    image: "/images/avatar/avatar-5.jpg",
    patientName: "Daniel Brown",
    age: 50,
    gender: "Male",
    doctor: "Dr. Sarah Johnson",
    amount: 300,
    department: "Surgery",
    appointmentDate: "24-10-2025",
    appointmentTime: "03:30 PM",
    status: "Paid",
    isComplate: true,
    contact: "+1 678 901 234",
  },
  {
    id: 6,
    image: "/images/avatar/avatar-6.jpg",
    patientName: "Sophia Wilson",
    age: 45,
    gender: "Female",
    doctor: "Dr. James Anderson",
    department: "Neurology",
    appointmentDate: "25-10-2025",
    amount: 180,
    appointmentTime: "01:15 PM",
    status: "Unpaid",
    isComplate: false,
    contact: "+1 789 012 345",
  },
  {
    id: 7,
    image: "/images/avatar/avatar-7.jpg",
    patientName: "Christopher Martinez",
    age: 37,
    amount: 220,
    gender: "Male",
    doctor: "Dr. Emma Thomas",
    department: "Check-up",
    appointmentDate: "26-10-2025",
    appointmentTime: "08:30 AM",
    status: "Paid",
    isComplate: true,
    contact: "+1 890 123 456",
  },
  {
    id: 8,
    image: "/images/avatar/avatar-8.jpg",
    patientName: "Olivia Taylor",
    age: 29,
    amount: 190,
    gender: "Female",
    doctor: "Dr. Henry Wilson",
    department: "Emergency",
    appointmentDate: "27-10-2025",
    appointmentTime: "04:00 PM",
    status: "Paid",
    isComplate: true,
    contact: "+1 901 234 567",
  },
  {
    id: 9,
    image: "/images/avatar/avatar-9.jpg",
    patientName: "James Anderson",
    age: 55,
    gender: "Male",
    amount: 210,
    doctor: "Dr. Isabella White",
    department: "Orthopedics",
    appointmentDate: "28-10-2025",
    appointmentTime: "07:00 PM",
    status: "Unpaid",
    isComplate: false,
    contact: "+1 012 345 678",
  },
  {
    id: 10,
    image: "/images/avatar/avatar-10.jpg",
    patientName: "Emma Thomas",
    age: 31,
    gender: "Female",
    doctor: "Dr. Daniel Parker",
    department: "Consultation",
    appointmentDate: "29-10-2025",
    amount: 230,
    appointmentTime: "06:30 AM",
    status: "Paid",
    isComplate: false,
    contact: "+1 123 456 789",
  },
  {
    id: 11,
    image: "/images/avatar/avatar-1.jpg",
    patientName: "Liam Johnson",
    age: 42,
    gender: "Male",
    doctor: "Dr. Sophia Brown",
    amount: 240,
    department: "General Medicine",
    appointmentDate: "30-10-2025",
    appointmentTime: "10:00 AM",
    status: "Paid",
    isComplate: false,
    contact: "+1 234 567 890",
  },
  {
    id: 12,
    image: "/images/avatar/avatar-2.jpg",
    patientName: "Ava Martinez",
    age: 27,
    gender: "Female",
    amount: 260,
    doctor: "Dr. Michael Davis",
    department: "Cardiology",
    appointmentDate: "31-10-2025",
    appointmentTime: "11:30 AM",
    status: "Unpaid",
    isComplate: false,
    contact: "+1 345 678 901",
  },
  {
    id: 13,
    image: "/images/avatar/avatar-3.jpg",
    patientName: "Noah Wilson",
    age: 38,
    gender: "Male",
    amount: 280,
    doctor: "Dr. Emily Taylor",
    department: "Dental",
    appointmentDate: "01-11-2025",
    appointmentTime: "09:45 AM",
    status: "Paid",
    isComplate: true,
    contact: "+1 456 789 012",
  },
  {
    id: 14,
    image: "/images/avatar/avatar-4.jpg",
    patientName: "Isabella Brown",
    age: 33,
    gender: "Female",
    amount: 300,
    doctor: "Dr. Christopher Johnson",
    department: "Dermatology",
    appointmentDate: "02-11-2025",
    appointmentTime: "02:15 PM",
    status: "Paid",
    isComplate: true,
    contact: "+1 567 890 123",
  },
  {
    id: 15,
    image: "/images/avatar/avatar-5.jpg",
    patientName: "Mason Davis",
    age: 48,
    gender: "Male",
    amount: 320,
    doctor: "Dr. Olivia Martinez",
    department: "Surgery",
    appointmentDate: "03-11-2025",
    appointmentTime: "04:00 PM",
    status: "Unpaid",
    isComplate: false,
    contact: "+1 678 901 234",
  },
];
